spring.application.name=apibiblioteca

server.port=${PORT:8080}

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

spring.jackson.time-zone=America/Lima

# ==========================================
# CONEXIÓN A LA BASE DE DATOS EN RAILWAY
# ==========================================

# Spring armará la URL usando los datos que pusiste en Railway
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQL_DATABASE}

# El usuario por defecto en Railway suele ser root
spring.datasource.username=root

# Toma la contraseña que tienes en tus variables
spring.datasource.password=${MYSQL_ROOT_PASSWORD}

# Driver para conectarse a MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# (Opcional) Si usas JPA/Hibernate para que actualice las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
