sonar.host.url=http://localhost:9000
sonar.token=squ_067ccb82a5964c72605947427a3995b759b8e9ab

sonar.projectKey=backend
sonar.projectName=Backend (Spring Boot)
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=**/entity/**,**/dto/**,**/controller/**,**/generic/**,**/*Config.java,**/JwtFilter.java,**/ApibibliotecaApplication.java,**/WebConfig.java,**/BusinessAuthor.java,**/BusinessBook.java,**/BusinessCategory.java,**/BusinessStats.java,**/JwtService.java
sonar.exclusions=**/entity/**,**/dto/**,**/controller/**,**/generic/**,**/*Config.java,**/JwtFilter.java,**/ApibibliotecaApplication.java,**/WebConfig.java,**/BusinessReservation.java,**/BusinessLoan.java,**/BusinessAuthor.java,**/BusinessBook.java,**/BusinessCategory.java,**/BusinessStats.java,**/JwtService.java
